services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        user: root
        restart: unless-stopped
        ports: 
        - "${MSSQL_PORT:?error}:1433"
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_DATABASE=master
        - MSSQL_USER=sa
        - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD:?error}
        - MSSQL_PID="Express"
        - DATABASE_IP=${DATABASE_IP:?error}
        - BACKEND_IP=${BACKEND_IP:?error}
        - FRONTEND_IP=${FRONTEND_IP:?error}
        volumes:
        - mssqlsystem:/var/opt/mssql
        - mssqluser:/var/opt/sqlserver
        networks:
            internal_network:
                ipv4_address: ${DATABASE_IP:?error}
    backend:
        depends_on:
        - db
        build: "./backend"
        ports:
        - "${BACKEND_PORT:?error}:80"
        restart: unless-stopped
        environment:
        - DATABASE_IP=${DATABASE_IP:?error}
        - BACKEND_IP=${BACKEND_IP:?error}
        - FRONTEND_IP=${FRONTEND_IP:?error}
        networks:
            internal_network:
                ipv4_address: ${BACKEND_IP:?error}
    frontend:
        depends_on:
        - backend
        build: "./frontend"
        ports:
        - "${FRONTEND_PORT:?error}:80"
        restart: unless-stopped
        environment:
        - DATABASE_IP=${DATABASE_IP:?error}
        - BACKEND_IP=${BACKEND_IP:?error}
        - FRONTEND_IP=${FRONTEND_IP:?error}    
        networks:
            internal_network:
                ipv4_address: ${FRONTEND_IP:?error}              
networks:
    internal_network:
        driver: bridge
        ipam:
            config:
            - subnet: 1.0.0.0/29
              gateway: 1.0.0.4        
volumes:
    mssqlsystem:
        driver: local
    mssqluser:
        driver: local        
