# https://stackoverflow.com/questions/46495855/restrict-branch-x-to-be-merged-only-from-one-specific-branch-y-in-github

name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != develop ]]; 
          then
            echo "Error: Pull request must come from 'develop' branch"
            exit 1
          fi