name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Iniciar el cluster de contenedores
        run: |
          cp /home/talleruser24/.env ./.env && docker compose up -d --build && echo "¡Cluster iniciado con éxito!"
